from cart_player.backend.domain.events import (
    BackupCartSaveProgressEvent,
    CartDataReadEvent,
    CartGameInstalledEvent,
    CartSaveBackupEvent,
    CartSaveErasedEvent,
    CartSaveWrittenEvent,
    EraseCartSaveProgressEvent,
    GameDataDeletedEvent,
    GameDataUpdatedEvent,
    GBXFlasherConfigurationUpdatedEvent,
    InstallCartGameProgressEvent,
    LocalMemoryConfigurationUpdatedEvent,
    WriteCartSaveProgressEvent,
)
