[tool.pytest.ini_options]
pythonpath = ["."]

[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
skip-string-normalization = 1

[tool.isort]
skip = ["__init__.py"]
line_length = 120
combine_as_imports = true
multi_line_output = 3
include_trailing_comma = true
profile = "black"
