SPECIAL_REGEX_PATTERN = r"\((\d{4}-\d{2}-\d{2})|(\d{2}-\d{2})|(v\d{1}.\d{1})|(\d{4})|(E3 \d{4})\)"
EXCLUDED_CHUNKS = {
    "(Kiosk, GameCube)",
    "(En,Nl)",
    "(En,Fr,De,Es,It,Nl,Pt,Sv,Da)",
    "(En,Nl,Sv,No,Da)",
    "(En,Fr,Nl)",
    "(Zh)",
    "(Korea)",
    "(En,Fr,De,Es,It,Nl,Sv,Da+En)",
    "(DS Expansion Cartridge)",
    "(Fr+En,Fr,De,Es,It)",
    "(Proto 2)",
    "(Fr,De)",
    "(En,Fr,De,Es,It,Nl)",
    "(Proto)",
    "(Proto 1)",
    "(En,Fr,De,Es,It,Nl+En,Fr,De,Es,Nl)",
    "(China)",
    "(En,Ja,Fr,De,Es+En,Ja)",
    "(Virtual Console)",
    "(SGB Enhanced)",
    "(NP)",
    "(Climax Entertainment)",
    "(Test Program)",
    "(Sample)",
    "(Imagineer)",
    "(En,Fr,De,Es+En,Fr,De,Es,It,Nl)",
    "(World)",
    "(Possible Proto)",
    "(Kiosk)",
    "(Majesco)",
    "(Es+En,Fr,De,Es,It)",
    "(Es,It+En,Es,It,Sv,Da)",
    "(De+Fr,De,Nl)",
    "(BPTP)",
    "(Fr+En,Fr,De,Es,It,Nl,Sv,Da)",
    "(En,Fr,De,Es,It,Sv,Da)",
    "(En,Ja,Fr,De,Es,It+En)",
    "(En,Fr,De,Es,It,Nl,Sv,Da)",
    "(USA)",
    "(Activision)",
    "(En,Fr,De,Es,It,Nl,Pt)",
    "(En,Es,It)",
    "(Castlevania Advance Collection)",
    "(France)",
    "(En,Fr,De,Es,It,Pt)",
    "(En,De,It)",
    "(En,Sv,No,Da,Fi)",
    "(En,Es,Nl)",
    "(Fr,De,Es)",
    "(Ubi Soft)",
    "(USA, Australia)",
    "(USA, Europe)",
    "(En,Fr,De)",
    "(Mindscape)",
    "(It,Nl)",
    "(En,De,Es)",
    "(En,Es,Nl+Fr,Nl)",
    "(En,Es,Nl+Es,It)",
    "(Program)",
    "(Beta 2)",
    "(En,Fr,De,Es,It+En)",
    "(En,Fr,De+En,Fr,De,Es,It)",
    "(Accolade)",
    "(En,Fr,De,Da)",
    "(Pirate)",
    "(En,Fr,De,Da+En,De)",
    "(Tech Demo)",
    "(En,Ja,Fr,De,Es+En,Ja,Fr,De,Es,It)",
    "(Fr,De,Nl)",
    "(United Kingdom)",
    "(Zoo Digital)",
    "(Netherlands)",
    "(En,Fr,De,It,Sv,No,Da,Fi)",
    "(En,Fr,De,Es,It,Da)",
    "(Germany)",
    "(En,Fr,De,Es,It,Nl,Sv)",
    "(En,Fr,De,Es,Nl)",
    "(En,Fr,De,Es,It,Nl,Pt,Sv)",
    "(Spain)",
    "(En,Es,It,Sv,Da)",
    "(En,Fr,It+Fr,Nl)",
    "(Fr,Nl+Fr,De,Nl)",
    "(Homebrew)",
    "(Fr,De,Es,It,Nl,Sv,Da)",
    "(Fr,Nl)",
    "(En)",
    "(En,Ja,Fr,De,Es)",
    "(En,Ja,Fr,De,Es,It)",
    "(Es,It+Es)",
    "(En,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi)",
    "(Taiwan)",
    "(En,Fr,De,Es,It,Sv)",
    "(3DS Virtual Console)",
    "(En,Fr,De,Es,It,Nl,Ca)",
    "(En+En,Es,It,Sv,Da)",
    "(En,Fr,De,Es,It,Nl+En,Fr,De,Es,It,Nl,Sv,No,Da,Fi)",
    "(En,Fr,De,Es,It,Nl,Sv,No,Da,Fi)",
    "(Beta)",
    "(En+En,Fr,De)",
    "(HAL Laboratory)",
    "(En,Ja,Fr,De,Es,It+En,Ja,Fr,De,Es)",
    "(Fr,De,Es,It)",
    "(Debug Version)",
    "(En,Fr,De,Es,It,Nl+En,Fr,De,Es,It)",
    "(En,Fr,De,Nl)",
    "(En,Fr,De,Es,It,Nl,Pt,Da)",
    "(Italy)",
    "(En,Fr,Es)",
    "(En,Ja,Fr,De,Es,Zh)",
    "(En,Fr)",
    "(En,Fr,De,Es,It,Fi)",
    "(Contra Anniversary Collection)",
    "(Japan)",
    "(Europe)",
    "(B5DJ)",
    "(En,Fr,De,Es,It,Nl,Sv,No,Da)",
    "(En,It)",
    "(En,Fr,It)",
    "(En,Fr,De,Es,It,Nl,Da)",
    "(En,Ja+En,Ja,Fr,De,Es,It)",
    "(IE Institute)",
    "(En,Fr,De,It,Nl,Sv)",
    "(En,Fr,Es,It,Nl,Pt,Da)",
    "(Proto 3)",
    "(Es,It)",
    "(BJJP)",
    "(Collection of SaGa)",
    "(En,Fr,De+En,Fr,De,Es)",
    "(En,Fr,De,Es,It)",
    "(En,De,Es,It)",
    "(Bright Version)",
    "(Phantasy Star Online Episode I & II)",
    "(Pokemon Box)",
    "(Unl)",
    "(Ja)",
    "(En,De)",
    "(Password Version)",
    "(En+En+En,Fr,De)",
    "(Alt)",
    "(En,Fr,Es,It)",
    "(DSI)",
    "(Earlier)",
    "(Es+En,Fr,De,Es,It,Nl,Sv,Da)",
    "(Collection of Mana)",
    "(En,Fr,De,Es,It,Nl,Pt,Sv,No,Da)",
    "(Not For Resale)",
    "(En,Fr,De,Es,It,Nl,Pt,Sv,No,Da,Fi,Pl)",
    "(En,Fr,De+Fr)",
    "(It+En,Fr,De,Es,It,Nl,Sv,Da)",
    "(Fr,De,Pt)",
    "(Seiken Densetsu Collection)",
    "(Denmark)",
    "(En,Fr,De,Es,It,Sv,No,Da,Fi)",
    "(En,It,Sv,No,Da)",
    "(De+En,Fr,De,Es,It,Nl,Sv,Da)",
    "(Debug)",
    "(Fr,Es)",
    "(Fr,De,Es,Nl)",
    "(July, 1992)",
    "(Sweden)",
    "(SRAM Version)",
    "(En,Fr,De+En)",
    "(Pokemon Stadium)",
    "(En,Fr,It+Es,It)",
    "(Promo)",
    "(En,Fr,De,It)",
    "(Fr+En)",
    "(En,Fr,Es,Nl)",
    "(Fr,De,Es,It,Sv)",
    "(En,Es)",
    "(Australia)",
    "(GB Compatible)",
    "(AFMJ)",
    "(En,Fr,De,It,Nl)",
    "(Vivendi)",
    "(Rev 1)",
    "(Disney Classic Games)",
    "(En,Ja,Fr,De)",
    "(BFWJ)",
    "(En+En,Fr,De,Es,It,Nl,Sv,Da)",
    "(En,Fr,De+De)",
    "(CGB+SGB Enhanced)",
    "(En,Ja)",
    "(Sv,No,Da,Fi)",
    "(Es,Pt)",
    "(Demo)",
    "(Beta 3)",
    "(En,Fr,De,Es)",
    "(En+En,Ja,Fr,De,Es)",
    "(En,Fr,De,Es,It,Sv+En,Fr,De,Es,It)",
    "(Es,It+It)",
    "(Hudson Soft)",
    "(Rumble Version)",
    "(En,Fr,Es,Pt)",
    "(En,De,Es,Nl)",
    "(Rev 2)",
    "(Beta 1)",
    "(GameCube)",
    "(Fr)",
    "(Dark Version)",
    "(Hot Mario Campaign)",
    "(En,No,Da)",
    "(All Unlocked)",
    "(Castlevania Anniversary Collection)",
}
