from enum import Enum


class ComponentKey(str, Enum):
    # Pop-up window selector buttons
    PLAY_SELECTOR_BUTTON = "-PLAY_SELECTOR_BUTTON-"
    DATA_SELECTOR_BUTTON = "-DATA_SELECTOR_BUTTON-"
    SETTINGS_SELECTOR_BUTTON = "-SETTINGS_SELECTOR_BUTTON-"

    # Buttons
    REFRESH_BUTTON = "-REFRESH_BUTTON-"
    FOLDER_BROWSE_MEMORY_FOLDER = "-FOLDER_BROWSE_MEMORY_FOLDER-"
    FOLDER_BROWSE_GAME_BOX_IMAGE_FILE = "-FOLDER_BROWSE_GAME_BOX_IMAGE_FILE-"
    OPEN_MEMORY_FOLDER = "-OPEN_BROWSE_MEMORY_FOLDER-"
    INSTALL_BUTTON = "-INSTALL_BUTTON-"
    BACKUP_BUTTON = "-BACKUP_BUTTON-"
    UPLOAD_BUTTON = "-UPLOAD_BUTTON-"
    ERASE_BUTTON = "-ERASE_BUTTON-"
    LAUNCH_BUTTON = "-LAUNCH_BUTTON-"
    END_SESSION = "-END_SESSION_BUTTON-"

    # Edit apply buttons
    EDIT_GAME_BOX_IMAGE_APPLY_BUTTON = "-EDIT_GAME_BOX_IMAGE_APPLY_BUTTON-"
    EDIT_GAME_NAME_APPLY_BUTTON = "-EDIT_GAME_NAME_APPLY_BUTTON-"
    EDIT_GAME_DESCRIPTION_APPLY_BUTTON = "-EDIT_GAME_DESCRIPTION_APPLY_BUTTON-"
    EDIT_GAME_PLATFORM_APPLY_BUTTON = "-EDIT_GAME_PLATFORM_APPLY_BUTTON-"
    EDIT_GAME_GENRE_APPLY_BUTTON = "-EDIT_GAME_GENRE_APPLY_BUTTON-"
    EDIT_GAME_DEVELOPER_APPLY_BUTTON = "-EDIT_GAME_DEVELOPER_APPLY_BUTTON-"
    EDIT_GAME_REGION_APPLY_BUTTON = "-EDIT_GAME_REGION_APPLY_BUTTON-"
    EDIT_GAME_RELEASE_APPLY_BUTTON = "-EDIT_GAME_RELEASE_APPLY_BUTTON-"
    EDIT_GAME_CRC_APPLY_BUTTON = "-EDIT_GAME_CRC_APPLY_BUTTON-"

    # Inputs
    INPUT_MEMORY_FOLDER = "-INPUT_MEMORY_FOLDER-"
    INPUT_GAME_BOX_IMAGE_FILE = "-INPUT_GAME_BOX_IMAGE_FILE-"
    INPUT_GAME_NAME = "-INPUT_GAME_NAME-"
    INPUT_GAME_DESCRIPTION = "-INPUT_GAME_DESCRIPTION-"
    INPUT_GAME_PLATFORM = "-INPUT_GAME_PLATFORM-"
    INPUT_GAME_GENRE = "-INPUT_GAME_GENRE-"
    INPUT_GAME_DEVELOPER = "-INPUT_GAME_DEVELOPER-"
    INPUT_GAME_REGION = "-INPUT_GAME_REGION-"
    INPUT_GAME_RELEASE = "-INPUT_GAME_RELEASE-"
    INPUT_GAME_CRC = "-INPUT_GAME_CRC-"

    # GameMetadataBox
    GAME_CART_BOX_IMAGE = "-GAME_CART_BOX_IMAGE-"
    GAME_NAME_FIELD = "-GAME_NAME_FIELD-"
    GAME_NAME_VALUE = "-GAME_NAME_VALUE-"
    GAME_DESCRIPTION_FIELD = "-GAME_DESCRIPTION_FIELD-"
    GAME_DESCRIPTION_VALUE = "-GAME_DESCRIPTION_VALUE-"
    GAME_PLATFORM_FIELD = "-GAME_PLATFORM_FIELD-"
    GAME_PLATFORM_VALUE = "-GAME_PLATFORM_VALUE-"
    GAME_GENRE_FIELD = "-GAME_GENRE_FIELD-"
    GAME_GENRE_VALUE = "-GAME_GENRE_VALUE-"
    GAME_DEVELOPER_FIELD = "-GAME_DEVELOPER_FIELD-"
    GAME_DEVELOPER_VALUE = "-GAME_DEVELOPER_VALUE-"
    GAME_REGION_FIELD = "-GAME_REGION_FIELD-"
    GAME_REGION_VALUE = "-GAME_REGION_VALUE-"
    GAME_RELEASE_FIELD = "-GAME_RELEASE_FIELD-"
    GAME_RELEASE_VALUE = "-GAME_RELEASE_VALUE-"
    GAME_CRC_FIELD = "-GAME_CRC_FIELD-"
    GAME_CRC_VALUE = "-GAME_CRC_VALUE-"

    # Progress bar
    DATA_WINDOW_PROGRESS_BAR = "-DATA_WINDOW_PROGRESS_BAR-"

    # Texts
    INSTALL_GAME_BOX_GAME_NAME = "-INSTALL_GAME_BOX_GAME_NAME-"
    DOWNLOAD_SAVE_BOX_SAVE_NAME = "-DOWNLOAD_SAVE_BOX_SAVE_NAME-"
    UPLOAD_SAVE_BOX_SAVE_NAMES_COMBO = "-UPLOAD_SAVE_BOX_SAVE_NAMES_COMBO-"
    PLAY_SAVE_BOX_SAVE_NAMES_COMBO = "-PLAY_SAVE_BOX_SAVE_NAMES_COMBO-"
    DATA_WINDOW_ETA = "-DATA_WINDOW_ETA-"
    GBX_FLASHER_PREFERRED_MODE_COMBO = "-GBX_FLASHER_PREFERRED_MODE_COMBO-"
