from enum import Enum


class ComponentKey(str, Enum):
    # Pop-up window selector buttons
    PLAY_SELECTOR_BUTTON = "-PLAY_SELECTOR_BUTTON-"
    DATA_SELECTOR_BUTTON = "-DATA_SELECTOR_BUTTON-"
    SETTINGS_SELECTOR_BUTTON = "-SETTINGS_SELECTOR_BUTTON-"

    # Buttons
    REFRESH_BUTTON = "-REFRESH_BUTTON-"
    FOLDER_BROWSE_MEMORY_FOLDER = "-FOLDER_BROWSE_MEMORY_FOLDER-"
    OPEN_MEMORY_FOLDER = "-OPEN_BROWSE_MEMORY_FOLDER-"
    INSTALL_BUTTON = "-INSTALL_BUTTON-"
    BACKUP_BUTTON = "-BACKUP_BUTTON-"
    UPLOAD_BUTTON = "-UPLOAD_BUTTON-"
    ERASE_BUTTON = "-ERASE_BUTTON-"
    LAUNCH_BUTTON = "-LAUNCH_BUTTON-"
    END_SESSION = "-END_SESSION_BUTTON-"

    # Inputs
    INPUT_MEMORY_FOLDER = "-INPUT_MEMORY_FOLDER-"

    # GameMetadataBox
    GAME_CART_BOX_IMAGE = "-GAME_CART_BOX_IMAGE-"
    GAME_CART_BOX_FIELD_NAME = "-GAME_CART_BOX_FIELD_NAME-"
    GAME_CART_BOX_VALUE_NAME = "-GAME_CART_BOX_VALUE_NAME-"
    GAME_CART_BOX_FIELD_DESCRIPTION = "-GAME_CART_BOX_FIELD_DESCRIPTION-"
    GAME_CART_BOX_VALUE_DESCRIPTION = "-GAME_CART_BOX_VALUE_DESCRIPTION-"
    GAME_CART_BOX_FIELD_PLATFORM = "-GAME_CART_BOX_FIELD_PLATFORM-"
    GAME_CART_BOX_VALUE_PLATFORM = "-GAME_CART_BOX_VALUE_PLATFORM-"
    GAME_CART_BOX_FIELD_GENRE = "-GAME_CART_BOX_FIELD_GENRE-"
    GAME_CART_BOX_VALUE_GENRE = "-GAME_CART_BOX_VALUE_GENRE-"
    GAME_CART_BOX_FIELD_DEVELOPER = "-GAME_CART_BOX_FIELD_DEVELOPER-"
    GAME_CART_BOX_VALUE_DEVELOPER = "-GAME_CART_BOX_VALUE_DEVELOPER-"
    GAME_CART_BOX_FIELD_REGION = "-GAME_CART_BOX_FIELD_REGION-"
    GAME_CART_BOX_VALUE_REGION = "-GAME_CART_BOX_VALUE_REGION-"
    GAME_CART_BOX_FIELD_RELEASE = "-GAME_CART_BOX_FIELD_RELEASE-"
    GAME_CART_BOX_VALUE_RELEASE = "-GAME_CART_BOX_VALUE_RELEASE-"

    # Progress bar
    DATA_WINDOW_PROGRESS_BAR = "-DATA_WINDOW_PROGRESS_BAR-"

    # Texts
    INSTALL_GAME_BOX_GAME_NAME = "-INSTALL_GAME_BOX_GAME_NAME-"
    DOWNLOAD_SAVE_BOX_SAVE_NAME = "-DOWNLOAD_SAVE_BOX_SAVE_NAME-"
    UPLOAD_SAVE_BOX_SAVE_NAMES_COMBO = "-UPLOAD_SAVE_BOX_SAVE_NAMES_COMBO-"
    PLAY_SAVE_BOX_SAVE_NAMES_COMBO = "-PLAY_SAVE_BOX_SAVE_NAMES_COMBO-"
    DATA_WINDOW_ETA = "-DATA_WINDOW_ETA-"
